Repository Money-Touch/FE, pull requests merged in 2025-08, with the labels that each got.

#60 ♻️ Refactor: Tailwind CSS 적용
  src/assets/images/auth/badge/Pencil.png
  src/assets/images/auth/badge/Pencil_Filled.png
  src/components/feed/PostItem.tsx
  src/components/feed/SearchBox.tsx
  src/components/feed/SkeletonPost.tsx
  src/components/feed/SortDropdown.tsx
  src/components/feed/feedDetail/CommentInput.tsx
  src/components/feed/feedDetail/CommentItem.tsx
  src/mocks/feed/feed.ts
  src/pages/auth/mypage/mybadge.tsx
  src/pages/feed/feed.tsx
  src/pages/feed/feedDetail.tsx
  src/styles/auth/mypage/mybadge.style.ts
  src/styles/feed/feed.style.ts
  src/styles/feed/feedDetail.style.ts
Labels: ✨ Feature

#66 ♻️ Refactor: auth 페이지 통신 구현 및 토큰 재발급 로직 수정
  src/assets/images/auth/signup/result/PFE.png
  src/assets/images/auth/signup/result/PFG.png
  src/assets/images/auth/signup/result/PTE.png
  src/assets/images/auth/signup/result/PTG.png
  src/assets/images/auth/signup/result/SFE.png
  src/assets/images/auth/signup/result/SFG.png
  src/assets/images/auth/signup/result/STE.png
  src/assets/images/auth/signup/result/STG.png
  src/components/auth/mypage/mypage/profile.tsx
  src/components/auth/signup/profile/profileForm.tsx
  src/components/auth/test/loading/spinner.tsx
  src/components/auth/test/mbti/mbti.tsx
  src/components/auth/test/result/result.tsx
  src/components/auth/test/result/resultForm.tsx
  src/hooks/auth/mypage/useMypageQuery.tsx
  src/hooks/auth/test/useOnboardingMutation.tsx
  src/hooks/auth/test/useResultQuery.tsx
  src/hooks/auth/token/useAutoTokenRefresh.tsx
  src/hooks/auth/token/useRefreshToken.tsx
  src/hooks/auth/token/useValidateToken.tsx
  src/mocks/auth/test/resultData.tsx
  src/pages/auth/mypage/mypage.tsx
  src/styles/auth/test/test.style.ts
  src/types/auth/mypage/mypage.ts
  src/types/auth/test/result.ts
  src/utils/common/loadImages.ts
Labels: ✨ Feature

#68 🐛 Fix: API 요청에 헤더 추가
  src/hooks/home/notify/useNotifications.ts
  src/hooks/home/record/useCategories.ts
  src/hooks/home/record/useSubmitRecord.ts
  src/hooks/home/routine/useRoutine.ts
  src/hooks/home/routine/useSearchRoutine.ts
Labels: 🐞 Bug

#70 ♻️ Refactor: mbti 결과 이미지 교체
  src/assets/images/auth/signup/result/PFEshadow.png
  src/assets/images/auth/signup/result/PFGshadow.png
  src/assets/images/auth/signup/result/PTEshadow.png
  src/assets/images/auth/signup/result/PTGshadow.png
  src/assets/images/auth/signup/result/SFEshadow.png
  src/assets/images/auth/signup/result/SFGshadow.png
  src/assets/images/auth/signup/result/STEshadow.png
  src/assets/images/auth/signup/result/STGshadow.png
  src/components/auth/mypage/mypage/menu/item-menu.tsx
  src/components/auth/signup/profile/profileForm.tsx
  src/components/auth/test/mbti/mbti.tsx
  src/components/auth/test/onboarding/onboarding.tsx
  src/components/auth/test/result/resultForm.tsx
  src/mocks/auth/test/resultData.tsx
  src/types/auth/test/result.ts
Labels: ✨ Feature

#71 ♻️ Refactor: 마이페이지 MY 피드 통신 연결
  src/components/auth/mypage/myfeed/grid/item-grid2.tsx
  src/components/auth/mypage/myfeed/grid/item-grid4.tsx
  src/components/auth/mypage/myfeed/grid/list-grid2.tsx
  src/components/auth/mypage/myfeed/grid/list-grid4.tsx
  src/components/home/main/consumptionWelcome.tsx
  src/hooks/auth/mypage/useFeedQuery.tsx
  src/mocks/auth/mypage/myfeed/gridData.tsx
  src/pages/auth/mypage/myfeed.tsx
  src/styles/auth/mypage/mypage.style.ts
  src/types/auth/mypage/myfeed.ts
Labels: ✨ Feature

#74 ✨ Feat: 랭킹 페이지 및 홈 랭킹 통신 완료
  dist/assets/Boss-13i-sXhv.png
  dist/assets/Fairy-Che0rtK0.png
  dist/assets/July_first-DZUmY8MY.png
  dist/assets/June_second-CJ8pTDi6.png
  dist/assets/Lover-Dui0g0fD.png
  dist/assets/Master-DUrWNBWG.png
  dist/assets/May_third-v9tC7wCM.png
  dist/assets/PFE-C_FwtqlF.png
  dist/assets/PFEshadow-NWbCyUIk.png
  dist/assets/PFG-cXkkcpOy.png
  dist/assets/PFGshadow-BAiBYCIu.png
  dist/assets/PTE-DXO3k3Cg.png
  dist/assets/PTEshadow-eFSsLeEM.png
  dist/assets/PTG-OBI_MjW3.png
  dist/assets/PTGshadow-DbAiasKu.png
  dist/assets/SFE-FoLT45C-.png
  dist/assets/SFEshadow-D59ZgytW.png
  dist/assets/SFG-kdA8GPW8.png
  dist/assets/SFGshadow-Drc9kwa2.png
  dist/assets/STE-AyRQidec.png
  dist/assets/STEshadow-D-2g_aVD.png
  dist/assets/STG-CFsEnnUE.png
  dist/assets/STGshadow-BbXgafxn.png
  dist/assets/basic.-NmUowluZ.png
  dist/assets/basic2-hjvYTTK-.png
  dist/assets/budget-CsTRZzir.png
  dist/assets/cafe-Bz2vHRzI.png
  dist/assets/eat-DIwV5GjK.png
  dist/assets/fixedcost-DwnalL45.png
  dist/assets/index-3uMSzanL.css
  dist/assets/index-Dqq_WD95.js
  dist/assets/index-DsUz2i7t.js
  dist/assets/index-wCkNUlm6.css
  dist/assets/play-BBpLgax7.png
  dist/index.html
  src/components/home/main/consumptionRanking.tsx
  src/components/home/ranking/myRank.tsx
  src/components/home/ranking/otherUser.tsx
  src/components/home/ranking/topUser.tsx
  src/hooks/home/ranking/useRanking.ts
  src/mocks/home/mockRankingData.ts
  src/pages/home/ranking.tsx
  src/types/home/ranking.ts
  src/utils/home/getRankChangeIcon.ts
Labels: ✨ Feature

#79 ✨ Feat: 가계부 UI 3차
  src/pages/money/addday.tsx
  src/pages/money/money.tsx
  src/pages/money/registration.tsx
  src/pages/money/routineregistration.tsx
Labels: ✨ Feature

#82 🐛 Fix: 헤더 수정
  src/styles/header/header.style.ts
Labels: 🐞 Bug

#83 ✨ Feat: 소비루틴 홈, 상세 조회 통신 완료
  src/components/home/main/consumptionRoutine.tsx
  src/components/home/routine/budgetList.tsx
  src/hooks/home/routine/useRoutineDetail.ts
  src/hooks/home/routine/useRoutinePreview.ts
  src/mocks/home/mockRoutineData.ts
  src/mocks/home/mockUser.ts
  src/pages/home/routinedetail.tsx
  src/types/home/routine.ts
Labels: ✨ Feature

#107 🐛 Fix: 헤더 title 치우침 해결
  src/styles/header/header.style.ts
Labels: 🐞 Bug

#109 ✨ Feat: 가계부 통신 연결, 일일 날짜 UI 수정
  package-lock.json
  package.json
  src/hooks/money/fixedcost/useFixedCostDeleteMutation.ts
  src/hooks/money/routine/useCreateRoutineMutation.ts
  src/hooks/money/routine/useMyRoutineDetailQuery.ts
  src/hooks/money/routine/useMyRoutinesQuery.ts
  src/hooks/money/routine/useUploadRoutineImageMutation.ts
  src/pages/money/addday.tsx
  src/pages/money/fixedcost.tsx
  src/pages/money/money.tsx
  src/pages/money/preview.tsx
  src/pages/money/routine.tsx
  src/pages/money/routineregistration.tsx
  src/styles/budget/fixedcost.styles.ts
  src/styles/budget/money.styles.ts
Labels: ✨ Feature

#111 ✨ Feat: 가계부 UI 리팩토링
  src/pages/money/routineregistration.tsx
  src/styles/budget/routineregistration.styles.ts
Labels: ✨ Feature

#112 🎨 Design: 가계부 관련 헤더, 푸터 UI 수정
  src/pages/money/fixedcost.tsx
  src/pages/money/money.tsx
  src/pages/money/registration.tsx
  src/styles/budget/addcategory.styles.ts
  src/styles/budget/fixedcost.styles.ts
  src/styles/budget/money.styles.ts
  src/styles/budget/myroutine.styles.ts
  src/styles/budget/registration.styles.ts
  src/styles/budget/routine.styles.ts
  src/styles/budget/routineregistration.styles.ts
Labels: ✨ Feature

#114 ✨ Feat: 가계부 UI 리팩토링
  src/pages/money/money.tsx
  src/styles/budget/money.styles.ts
  src/styles/budget/routine.styles.ts
Labels: ✨ Feature

#116 🎨 Design: 가계부 예산 등록, 카테고리 추가 tailwindCSS로 변경
  src/pages/money/addcategory.tsx
  src/pages/money/registration.tsx
  src/styles/budget/addcategory.styles.ts
  src/styles/budget/registration.styles.ts
  src/styles/common/globalStyle.css
Labels: ✨ Feature

#120 ✨ Feat:가계부 UI 리팩토링
  src/pages/money/fixedcost.tsx
  src/pages/money/myroutine.tsx
  src/pages/money/preview.tsx
  src/pages/money/routine.tsx
  src/pages/money/routineregistration.tsx
  src/styles/budget/fixedcost.styles.ts
  src/styles/budget/myroutine.styles.ts
  src/styles/budget/routine.styles.ts
  src/styles/budget/routineregistration.styles.ts
  src/styles/common/globalStyle.css
Labels: ✨ Feature

#121 🎨 Design: 가계부 페이지 tailwindCSS로 변경
  src/styles/budget/addcategory.styles.ts
  src/styles/budget/registration.styles.ts
Labels: ✨ Feature

#123 🎨 Design: 일일 등록 UI 수정
  src/styles/budget/addday.styles.ts
Labels: ✨ Feature

#133 🐛 Fix: 사진, 메모 섹션 필수 표시 제거 및 ModalBox 위치 조정
  src/components/home/record/imageSection.tsx
  src/components/home/record/memoSection.tsx
  src/components/home/record/title.tsx
  src/styles/home/modal.style.ts
Labels: 🐞 Bug

#142 ✨ Feat: budgetId state로 전달
  src/pages/home/routinedetail.tsx
Labels: ✨ Feature

#144 👽 Feat: 타인의 소비루틴 반영 API 연결
  src/components/auth/login/kakao/kakao.tsx
  src/hooks/money/addday/useCategoryQuery.tsx
  src/hooks/money/money/useFixedCostQuery.tsx
  src/hooks/money/registration/useRoutineDetailQuery.tsx
  src/hooks/money/registration/useRoutineMutation.tsx
  src/pages/money/addday.tsx
  src/pages/money/money.tsx
  src/pages/money/registration.tsx
  src/types/money/addday/addday.ts
  src/types/money/registration/registration.ts
  src/types/money/registration/routine.ts
  src/types/money/registration/routineDetail.ts
Labels: ✨ Feature

#146 ✨ Feat: 소비기록 중복 등록 방지 및 완료 버튼 로딩 상태 표시 추가
  src/components/home/record/submitButton.tsx
  src/pages/home/record.tsx
Labels: 🐞 Bug, ✨ Feature

#147 🐛 Fix: budgetList가 undefined일 때 map 오류 방지
  src/components/home/routine/budgetList.tsx
Labels: 🐞 Bug

#149 ✨ Feat: 가계부 UI 리팩토링
  src/assets/images/budget/etc.png
  src/hooks/money/routine/useMyRoutinesQuery.ts
  src/pages/money/addcategory.tsx
  src/pages/money/money.tsx
  src/pages/money/routine.tsx
  src/styles/budget/money.styles.tsx
Labels: ✨ Feature

#151 ✨ Feat: 가계부 UI 리팩토링
  src/pages/money/money.tsx
  src/pages/money/registration.tsx
Labels: ✨ Feature

#157 🐛 Fix: 스크롤바로 인한 UI 깨짐 오류 및 해시태그 중복 key 오류 해결
  src/components/home/routine/routineCard.tsx
  src/pages/home/notify.tsx
  src/pages/home/record.tsx
  src/pages/home/routine.tsx
  src/pages/home/routinedetail.tsx
  src/styles/home/notify.style.ts
  src/styles/home/record.style.ts
  src/styles/home/routine.style.ts
Labels: 🐞 Bug

#171 🎨 Design: 푸터에 따른 여백 변경
  src/components/auth/test/onboarding/onboarding.tsx
  src/pages/auth/mypage/myfeed.tsx
  src/pages/auth/mypage/mypage.tsx
  src/pages/money/money.tsx
  src/styles/auth/mypage/myfeed.style.ts
  src/styles/auth/mypage/mypage.style.ts
  src/styles/budget/money.styles.tsx
Labels: ✨ Feature

#172 👽 Fix: 소비루틴 등록 미리보기 이미지 통신 완료
  dist/assets/NoBadge-B2wjHJI0.png
  dist/assets/NoBadge-B4l1gRD5.svg
  dist/assets/etc-GTQ7dXAM.png
  dist/assets/index-D6O1WE-v.js
  dist/assets/index-DYA7Wda4.css
  dist/assets/index-Jwc3ocM7.css
  dist/assets/index-nt8w9XQR.js
  dist/index.html
  src/hooks/money/routine/useUploadRoutineImageMutation.ts
  src/pages/money/money.tsx
  src/pages/money/routineregistration.tsx
Labels: ✨ Feature

#173 👽 Fix: 소비루틴 등록 수정 오류 개선
  src/pages/money/routine.tsx
Labels: ✨ Feature
